package org.allenai.pipeline.spark

import java.net.URI

import org.allenai.pipeline._
import org.allenai.pipeline.s3.S3Pipeline

import com.amazonaws.auth.BasicAWSCredentials
import com.typesafe.config.Config
import org.apache.spark.SparkContext
import org.apache.spark.rdd.RDD

import scala.reflect.ClassTag

/** Created by rodneykinney on 5/24/15.
  */
trait SparkPipeline extends Pipeline {
  def sparkContext: SparkContext

  def persistRdd[T: ClassTag: StringSerializable](
    original: Producer[RDD[T]],
    suffix: String = ""
  ) = {
    val io = new PartitionedRddIo[T](sparkContext)
    val path = s"data/${autoGeneratedPath(original, io)}$suffix"
    val artifact = createArtifact[PartitionedRddArtifact[FlatArtifact]](path)
    persist(original, io, artifact)
  }

  override def urlToArtifact = UrlToArtifact.chain(super.urlToArtifact, CreateRddArtifacts.fromFileUrls)
}

trait SparkS3Pipeline extends SparkPipeline with S3Pipeline {
  override def urlToArtifact = UrlToArtifact.chain(super.urlToArtifact, CreateRddArtifacts.fromS3Urls(credentials))
}

trait ConfiguredSparkPipeline extends SparkPipeline with ConfiguredPipeline {
  def optionallyPersistRdd[T: ClassTag: StringSerializable](
    original: Producer[RDD[T]],
    stepName: String,
    suffix: String = ""
  ) = {
    val io = new PartitionedRddIo[T](sparkContext)
    optionallyPersist(original, stepName, io, suffix)
  }
}

object SparkPipeline {
  def apply(
    sc: SparkContext,
    rootUrl: URI,
    awsCredentials: BasicAWSCredentials = null
  ) =
    awsCredentials match {
      case null =>
        new SparkPipeline {
          override def rootOutputUrl = rootUrl
          override def sparkContext: SparkContext = sc
        }
      case _ =>
        new SparkS3Pipeline {
          override def rootOutputUrl = rootUrl
          override def credentials = awsCredentials

          override def sparkContext: SparkContext = sc
        }
    }

  def configured(
    cfg: Config,
    sc: SparkContext,
    awsCredentials: BasicAWSCredentials = null
  ) =
    awsCredentials match {
      case null =>
        new ConfiguredSparkPipeline {
          override def sparkContext: SparkContext = sc

          override val config: Config = cfg
        }
      case _ =>
        new ConfiguredSparkPipeline with SparkS3Pipeline {
          override def sparkContext: SparkContext = sc

          override val config: Config = cfg

          override def credentials = awsCredentials

        }
    }
}

